version: '3'
services:
  mongo: 
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongo_user}
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_pass}
    ports:
      - 27017:27017
  redis:
    image: redis:alpine3.17
    ports:
      - 6379:6379
    entrypoint: 'redis-server'
    # redis-cli to enter redis
  backend:
    image: ${docker_image_BE}:${docker_tag_BE}
    tty: true 
    restart: unless-stopped
    volumes: 
      - ./backend/shortenerBE:/usr/bin/shortenerBE
    ports:
      - 8080:8080
    env_file:
      - shared.env

  # frontend:
  #   image: ${docker_image_FE}:${docker_tag_FE}
  #   restart: unless-stopped
  #   volumes: 
  #     - ./frontend/shortener-fe:/usr/bin/shortener-fe
  #   ports:
  #     - 8081:8080