version: '3'
services:
  backend:
    image: ${docker_image_BE}:${docker_tag_BE}
    tty: true 
    volumes: 
      - ./backend/shortenerBE:/usr/bin/shortenerBE
    ports:
      - 8080:8080

  frontend:
    image: ${docker_image_FE}:${docker_tag_FE}
    tty: true 
    volumes: 
      - ./froentend/shortenerFE:/usr/bin/shortenerFE
    ports:
      - 8081:8081