version: '3.1'
services:
  backend:
    image: ${docker_image_BE}:${docker_tag_BE}
    stdin_open: true
    tty: true 
    command: go run main.go
    volumes: 
      - ./be:/usr/bin/shortenerBE
    ports:
      - 8080:8080